AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/**/*.rb
    - tmp/*
    - Rakefile
    - test/dummy/**/*
    - "*.gemspec"

require:
  - rubocop-performance
  - rubocop-rails

Metrics/LineLength:
  Max: 119 # line length on GitHub's PR pages

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 14
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/AbcSize:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/AndOr:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - sandbox
    - production

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/DateTime:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
